export const DEFAULTS = {
  BRANCH_PREFIX: 'fix/crash-',
  MAX_TURNS: 100,
  ALLOWED_TOOLS: ['Read', 'Edit', 'Write', 'Bash', 'Grep', 'Glob', 'WebSearch', 'WebFetch'],
  PR_LABELS: ['crash-fix', 'auto-generated'],
  DRY_RUN: false,
} as const;

/** @deprecated npm installation is deprecated. Use native install instead. */
export const CLAUDE_CLI_PACKAGE = '@anthropic-ai/claude-code';

export const CLAUDE_INSTALL_URL_UNIX = 'https://claude.ai/install.sh';
export const CLAUDE_INSTALL_URL_WINDOWS = 'https://claude.ai/install.cmd';

export const BRANCH_NAME_MAX_LENGTH = 100;

export const COMMIT_MESSAGE_PREFIX = 'fix(crash): ';

export const PR_BODY_TEMPLATE = [
  '## Crash Report Fix',
  '',
  '**Report ID:** `{{report_id}}`',
  '**Hash:** `{{crash_report_hash}}`',
  '**Application:** {{name}} v{{version}}',
  '**Platform:** {{platform}}',
  '',
  '### Root Cause',
  '',
  '{{root_cause}}',
  '',
  '### Solution',
  '',
  '{{solution}}',
  '',
  '### Changes Made',
  '',
  '{{changes_made}}',
  '',
  '### Files Modified',
  '',
  '{{files}}',
  '',
  '### Test Plan (Reviewer, if needed)',
  '',
  '{{test_plan}}',
  '',
  '---',
  '',
  '> This PR was automatically generated by [AI Code Issue Resolution](https://github.com/nospoon-ai/code-issue-resolution) using Claude Code CLI.',
  '> **Cost:** ${{cost}} USD',
  '',
  'Please review the changes carefully before merging.',
].join('\n');
